import { Database, FileText, Plus, Search, UploadCloud } from "lucide-react";
import { useState } from "react";
import type { KnowledgeDocument } from "../types";
import { StatusBadge } from "../components/ui/StatusBadge";
import { SectionHeader } from "../components/ui/SectionHeader";
import { Panel } from "../components/ui/Panel";
import { EmptyState } from "../components/ui/EmptyState";

export function KnowledgePage({ documents }: { documents: KnowledgeDocument[] }) { const [query, setQuery] = useState(""); const filtered = documents.filter((document) => document.name.toLowerCase().includes(query.toLowerCase())); return <div className="page-stack"><SectionHeader eyebrow="LOCAL KNOWLEDGE" title="Knowledge base" description="Ground agent responses in documents that stay within your environment." action={<button className="primary-button"><Plus size={16} /> Add document</button>} /><div className="knowledge-overview"><Panel className="knowledge-stat"><div className="knowledge-stat-icon"><Database size={19} /></div><div><span>Total indexed chunks</span><strong>300</strong><small>Across {documents.length} documents</small></div></Panel><Panel className="knowledge-stat"><div className="knowledge-stat-icon blue"><FileText size={19} /></div><div><span>Supported material</span><strong>PDF · DOCX</strong><small>OCR available for scans</small></div></Panel><Panel className="knowledge-upload"><UploadCloud size={21} /><div><strong>Drop files to ingest</strong><span>Documents are chunked and embedded locally.</span></div><button className="outline-button">Browse</button></Panel></div><Panel className="documents-panel"><div className="documents-toolbar"><div><p className="eyebrow">DOCUMENT LIBRARY</p><h3>Available sources</h3></div><div className="search-field"><Search size={16} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search documents" /></div></div>{filtered.length ? <div className="document-table"><div className="document-row document-header"><span>Document</span><span>Status</span><span>Chunks</span><span>Updated</span><span /></div>{filtered.map((document) => <div className="document-row" key={document.id}><div className="document-name"><span className="file-icon"><FileText size={16} /></span><div><strong>{document.name}</strong><span>{document.type} · {document.size}</span></div></div><StatusBadge status={document.status} /><span className="document-value">{document.chunks || "--"}</span><span className="document-value">{document.updatedAt}</span><button className="row-menu">•••</button></div>)}</div> : <EmptyState icon={Search} title="No documents found" description="Try a different document name." />}</Panel></div>; }
