import { Activity, AlertTriangle, CheckCircle2, Eye, LockKeyhole, Network, ShieldCheck } from "lucide-react";
import type { HealthStatus } from "../types";
import { previewSecurity } from "../data/demoData";
import { SectionHeader } from "../components/ui/SectionHeader";
import { Panel } from "../components/ui/Panel";
import { StatusBadge } from "../components/ui/StatusBadge";
import { SecurityPanel } from "../components/security/SecurityPanel";

export function SecurityPage({ health }: { health: HealthStatus }) { return <div className="page-stack"><SectionHeader eyebrow="TRUST CENTER" title="Security center" description="Visibility into where your work is processed and what evidence is available." action={<button className="outline-button"><Activity size={15} /> Refresh status</button>} /><div className="security-hero"><div className="security-hero-copy"><div className="large-security-icon"><ShieldCheck size={27} /></div><div><p className="eyebrow">PROCESSING BOUNDARY</p><h3>Designed to keep work close.</h3><p>Every core workflow is intended to run on infrastructure you control. The indicators below reflect what the connected backend can currently prove.</p></div></div><StatusBadge status={previewSecurity.measured ? "connected" : "unavailable"} label={previewSecurity.measured ? "Evidence verified" : "Evidence unavailable"} /></div><div className="security-grid"><SecurityPanel health={health} security={previewSecurity} /><Panel className="checks-panel"><div className="panel-heading"><div><p className="eyebrow">RUNTIME CHECKS</p><h3>Environment status</h3></div><Eye size={19} /></div><div className="check-item"><span className="check-icon check-muted"><Network size={16} /></span><div><strong>Network egress measurement</strong><span>Requires `/api/security/status`</span></div><StatusBadge status="unavailable" /></div><div className="check-item"><span className="check-icon check-muted"><LockKeyhole size={16} /></span><div><strong>Local model endpoint</strong><span>{health.connected ? "FastAPI is reachable" : "No backend connection"}</span></div><StatusBadge status={health.connected ? "connected" : "unavailable"} /></div><div className="check-item"><span className="check-icon check-muted"><ShieldCheck size={16} /></span><div><strong>Sandbox isolation</strong><span>Requires backend sandbox integration</span></div><StatusBadge status="unavailable" /></div><div className="security-warning"><AlertTriangle size={16} /><span>Do not treat unavailable measurements as proof of zero external traffic.</span></div></Panel></div><Panel className="principles-panel"><CheckCircle2 size={18} /><div><strong>Security principle</strong><p>Local execution should be demonstrated with evidence, not assumed from the interface. This screen intentionally reports missing measurements instead of inventing them.</p></div></Panel></div>; }
