import { FileCode2, FileText, Image, Paperclip, ShieldCheck, Sparkles, UploadCloud, X } from "lucide-react";
import { useRef, useState } from "react";
import type { CreateTaskInput, TaskType } from "../../types";

const taskOptions: { type: TaskType; label: string; detail: string; icon: typeof FileText }[] = [{ type: "document", label: "Document analysis", detail: "Reports, notes and approvals", icon: FileText }, { type: "coding", label: "Coding agent", detail: "Generate and verify code", icon: FileCode2 }, { type: "vision", label: "Vision review", detail: "Images and scanned documents", icon: Image }, { type: "general", label: "Local reasoning", detail: "Ask your private model", icon: Sparkles }];

export function TaskComposer({ onSubmit, submitting }: { onSubmit: (input: CreateTaskInput) => void; submitting: boolean }) {
  const [type, setType] = useState<TaskType>("document"); const [title, setTitle] = useState("Inspection report to approval note"); const [prompt, setPrompt] = useState("Analyze the attached inspection report, identify actionable findings, and draft an approval note using relevant local procedures."); const [file, setFile] = useState<File>(); const inputRef = useRef<HTMLInputElement>(null);
  return <form className="composer-form" onSubmit={(event) => { event.preventDefault(); if (prompt.trim()) onSubmit({ title: title.trim() || "Untitled task", prompt: prompt.trim(), type, file }); }}><div className="composer-section"><label className="form-label">Choose a workflow</label><div className="workflow-grid">{taskOptions.map((option) => { const Icon = option.icon; return <button type="button" key={option.type} className={`workflow-option ${type === option.type ? "selected" : ""}`} onClick={() => setType(option.type)}><span className="workflow-icon"><Icon size={17} /></span><span><strong>{option.label}</strong><small>{option.detail}</small></span>{type === option.type && <span className="selected-mark">✓</span>}</button>; })}</div></div><div className="composer-section"><label htmlFor="task-title" className="form-label">Task name</label><input id="task-title" value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Give this task a name" /></div><div className="composer-section"><label htmlFor="task-prompt" className="form-label">Instruction <span>Be specific about the outcome you need</span></label><textarea id="task-prompt" value={prompt} onChange={(event) => setPrompt(event.target.value)} rows={6} placeholder="What should the local agent do?" /></div><div className="composer-section"><label className="form-label">Reference material <span>Optional</span></label><input ref={inputRef} type="file" hidden onChange={(event) => setFile(event.target.files?.[0])} /><button type="button" className={`dropzone ${file ? "has-file" : ""}`} onClick={() => inputRef.current?.click()}>{file ? <><span className="uploaded-icon"><FileText size={18} /></span><span><strong>{file.name}</strong><small>{(file.size / 1024 / 1024).toFixed(2)} MB · Ready to process locally</small></span><X size={17} onClick={(event) => { event.stopPropagation(); setFile(undefined); }} /></> : <><UploadCloud size={21} /><span><strong>Drop a document here or browse</strong><small>PDF, DOCX, PNG or JPG · Processed on-premise</small></span><Paperclip size={18} /></>}</button></div><div className="composer-footer"><div className="local-notice"><ShieldCheck size={17} /><span><strong>Local processing</strong><small>No file is sent to a public AI service</small></span></div><button className="primary-button run-button" disabled={submitting || !prompt.trim()} type="submit">{submitting ? "Starting..." : "Run agent"}<Sparkles size={16} /></button></div></form>;
}
